# Generated by Django 2.2.6 on 2019-12-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'hacker'), (2, 'expert'), (3, 'company')], default=1),
            preserve_default=False,
        ),
    ]
