# Generated by Django 2.2.6 on 2020-01-02 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_wallet_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='wallet_address',
            new_name='address',
        ),
    ]
