# Generated by Django 2.2.6 on 2020-01-02 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hacker', '0002_submission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
