# Generated by Django 2.2.6 on 2020-01-02 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hacker', '0003_delete_submission'),
        ('company', '0010_auto_20200102_0552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submissionId', models.IntegerField(blank=True)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('poc', models.CharField(blank=True, max_length=200)),
                ('severity', models.CharField(blank=True, max_length=10)),
                ('resolve', models.BooleanField(default=False)),
                ('hacker', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hacker.Hacker')),
                ('program', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='company.Program')),
            ],
        ),
    ]
