# Generated by Django 2.2.6 on 2020-01-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='bounty',
            field=models.IntegerField(default=0),
        ),
    ]
