# Generated by Django 2.2.6 on 2020-01-02 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0003_submission_bounty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='resolve',
            new_name='resolved',
        ),
    ]
