# Generated by Django 2.2.6 on 2020-01-03 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0004_auto_20200102_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='bounty',
            field=models.BigIntegerField(default=0),
        ),
    ]
