# Generated by Django 2.2.6 on 2019-12-30 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='company',
            new_name='user',
        ),
    ]
