# Generated by Django 2.2.6 on 2019-12-30 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20191230_0303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='user',
            new_name='company',
        ),
    ]
