# Generated by Django 2.2.6 on 2019-12-30 09:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20191230_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='abiContract',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
