# Generated by Django 2.2.6 on 2019-12-30 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20191230_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='company',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='company.Company'),
        ),
    ]
