# Generated by Django 2.2.6 on 2019-12-30 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20191230_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='abiContract',
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='company.Program')),
            ],
        ),
    ]
