# Generated by Django 2.2.6 on 2020-01-02 05:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20191230_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='maxBounty',
        ),
        migrations.RemoveField(
            model_name='program',
            name='minBounty',
        ),
        migrations.AddField(
            model_name='contract',
            name='abi',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='baseBounty',
            field=models.IntegerField(null=True),
        ),
    ]
